version: 0.2

phases:
  pre_build:
    commands:
      # Authenticate Docker with ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528757828730.dkr.ecr.ap-south-1.amazonaws.com
     

  build:
    commands:
      # Build Docker image
      - docker build -t namespace/sampleproject .
      

  post_build:
    commands:
      # Push image to ECR
      - docker tag namespace/sampleproject:latest 528757828730.dkr.ecr.ap-south-1.amazonaws.com/namespace/sampleproject:latest
     
