#this is a sample buildspec.yml file for AWS CodeBuild
version: 0.3

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building...
  post_build:
    commands:
      - echo Done.
