version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528757828730.dkr.ecr.ap-south-1.amazonaws.com
      
build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t namespace/sampleproject .

post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker tag namespace/sampleproject:latest 528757828730.dkr.ecr.ap-south-1.amazonaws.com/namespace/sampleproject:latest

post_pushed:
    commands:
      - echo Post-push actions completed
      - push this image to your newly created AWS repository
      - docker push 528757828730.dkr.ecr.ap-south-1.amazonaws.com/namespace/sampleproject:latest

