version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Working directory: $(pwd)"
      - ls -la
      - npm install

  build:
    commands:
      - npm run build
