version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Example for Python:
      # - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the project..."
      # Example build commands:
      # - mvn package          # Java (Maven)
      # - go build -o app      # Go
      # - python setup.py build # Python

artifacts:
  files:
    - "**/*"  # Output all files (customize as needed)
